### ISSUE TITLE
Generators drop when players are offline

### ISSUE THREAD

**Issue by xdDirti** [arcadiadevs/infiniteforge-issues#2]
**Describe the bug**
Generators spawn their drops while players are offline. This not only causes less people to be online, but a huge performance effect, to the point where my server is hitting 6TPS.

**To Reproduce**
1. Place a generator down
2. Log on an alt and visit the generator
3. See it spawning in

**Comment by xdDirti** [comment]
This is an image of a player returning to their island after logging off overnight, they crashed the server upon joining
![image](https://github.com/arcadiadevs/infiniteforge-issues/assets/64794665/3fd9f3d6-b92d-4f8b-a0df-834604e1b4fc)

**Comment by hypermoist** [comment]
Im not a dev for the plugin, but it seems to me that the chunk they're in is not unloading causing it to continuously spawn this could be the fault of the plugin or it could be the fault of the world / area manager you use

**Comment by xdDirti** [comment]
> 
Offline player drops should not spawn at all, if the plugin is requesting drops top spawn then I would assume its loading and unloading the chunk in order to spawn it in

**Comment by OpenSource03** [comment]
That's been fixed in the latest update.
