### ISSUE TITLE
Add hex colour codes for titles / lore

### ISSUE THREAD

**Issue by hypermoist** [arcadiadevs/infiniteforge-issues#3]
**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

I'd like the ability to be able to use hex colour codes on the title / lore of generators

**Describe alternatives you've considered**

I have used default minecraft colour codes but it is not enough for customization 

**Additional context**

**Comment by OpenSource03** [comment]
Hex colors have been added. Use &#rrggbb.
