### ISSUE TITLE
Running /papi reload breaks placeholders

### ISSUE THREAD

**Issue by hypermoist** [arcadiadevs/infiniteforge-issues#6]
**Describe the bug**
When running /papi reload all infiniteforge placeholders break 

**To Reproduce**
1. /papi reload
2. Observe

**Expected behavior**
Should just reload and restore said values of called placeholder

**Screenshots**
https://cdn.discordapp.com/attachments/1126106060835532850/1128280995804758128/image.png

**Additional info (please complete the following information):**
 - Paper 1.20.1
 - no
 - 1.20.1

**Additional context**

**Comment by OpenSource03** [comment]
That's been fixed. The change will be published in the next update.
